// ẹ&#768
// ọ&#768
let words = {
	/////////////////////// Aa 
	exclamation: 'án',
	grasshopper: 'abaka',
	equal: 'abavo', 
	guilt: 'abé',
	wrestling: 'abémuó',
	thrice: 'abérha',
	sword: 'abẹrẹn',
	twice: 'abívẹ',
	"forked stick": 'áda',
	outing: 'ada',
	"three way junction": 'adérha',
	junction: 'adérha',
	position: 'ádié',
	part: 'ádié',
	bat: 'adján', 
	swallow: 'adjaọ&#768ghẹnẹ&#768',
	camphor: 'ádjeghwọghwọ',
	witch: 'adjené',
	wizad: 'adjené',
	pants: 'ádjọkrótẹgba',
	fan: 'adjudju',
	wheel: 'adjugẹ',
	menstruation: 'áfe',
	stadium: 'áfiéha',
	playground: 'áfiéha',
	"masquerade playground": 'áfiédjọ',
	rabbit: 'afiotọ',
	brain: 'afọrhe',
	crotch: 'agada <i><small>area between the legs</small></i>',
	gong: 'ágógó',
	bell: 'ágógó',
camp: 'agọ',
'temporary settlement': 'agọ',
court: 'aguare',
'oil bean seed': 'agbá (ogba)',
bridge: 'agbada',
altar: 'agbadarizobo',
cross: 'agbagba',
raffia: 'agbakara (ahwarihwa)',
'oil palm beetle': 'agbakara (ahwarihwa)',
chair: 'agbara (aga)',
dagger: 'agbogu',
echo: 'agboro',
chin: 'agbótọ',
placenta: 'agbọn (iride)',
matches: 'agbuna',
thunder: 'agbrara',
broom: 'aghán',
bead: 'óvwarha</br>úbivie <i><small>coral bead</small></i></br>aghighọn <i><small>chain of coral beads worn round the neck by chiefs</small></i></br>akpóno <i><small>very flat bead made from rubber or palm kernel shells</small></i></br>árhọvwefe <i><small>special bead worn on the neck like a bow-tie by traditional rulers</small></i>',
joy: 'aghọghọ (omavwerhovwẹ)',
happiness: 'aghọghọ',
bush: 'ághwá',
'bush dog': 'aghwaghwa',
wisdom: 'aghware',
hamster: 'aghwọn',
'bush rat': 'aghwọn',
announcement: 'aghwoghwo',
owl: 'áhe',
'owl like bird': 'áhe',
snoring: 'ahọnre', 
'sound of snoring': 'ahọnre',
pliers: 'ahwa',
sponge: 'ahworhẹ',
edo: 'aka <i><small>Urhobo name for the Edo (Bini) people and their language</small></i>',
'bitte kola': 'ákán',
gong: 'akaba <i><small>specie of gong</small></i>',
'snake monitor': 'akaínọrọ',
'bean cake': 'akara',
'water snail': 'akikọ&#768',
'metal trap': 'akobẹ <i><small>metal trap used for catching small animals such as rats</small></i>',
office: 'akoríruo',
'wooden slit gong': 'akuakua',
scorpion: 'akpakpasímagha',
'bald head': 'akpan',
baldness: 'akpan',
stool: 'ákpánurhé',
organ: 'ákpátá',
'mouth organ': 'ákpátá',
'way of life': 'akpéyéré',
'elephant tusk': 'akpẹ&#768rẹ',
'elephant horn': 'akpẹ&#768rẹ',
'elephant tusk horn': 'akpẹ&#768rẹ',
enjoyment: 'akpẹ&#768riọ',
padlock: 'akpẹ&#768rusiavwrẹ',
thanksgiving: 'ákpẹvwẹ',
world: 'akpọ',
life: 'akpọ',
'small lizard': 'akrẹ',
bell: 'ama',
angel: 'ámakáshe',
water: 'ame',
ink: 'ameọ&#768be',
ogogoro: 'amereka (agbakara), (ekaikai) <i><small>locally brewed gin, ogogoro</small></i>',
'groundnut oil': 'amerísaguẹ',
tears: 'amióviẹ',
who: 'amóno',
charm: "ẹbo</br>ámrádjẹ <i><small>charm for protection against the dead</small></i></br>áriákpa <i><small>charm for protection against any poisonous thing taken in by mouth</small></i></br>arido <i><small>charm for sharp remembrance/knowledge</small></i></br>atámu <i><small>charm for effective balance</small></i></br>átárhọvwe <i><small>charm for easy acceptance/answer</small></i></br>brávwárhé <i><small>charm for lightness</small></i></br>ávwíkpe <i><small>charm for postponing evil days such as death</small></i></br>égbésásá <i><small>charm for glorious dance</small></i></br>énivwọvo <i><small>charm for the exclusive attention of one's husband or lover</small></i></br>ẹkpo <i><small>charm for protection against machete attack</small></i></br>ẹ&#768lọhọ <i><small>charm for easy life</small></i></br>ibiabọ <i><small>charm for effective wrestling</small></i></br>inehweri <i><small>charm for love</small></i></br>ọbiúyovwi <i><small>charm for longevity</small></i></br>ọ&#768ghwẹ&#768fia <i><small>charm for protection against gun shot</small></i></br>ọtishé <i><small>charm for effective blow</small></i>",
cloth: 'amwá',
pride: 'anama',
april: 'ané <i><small>April</small></i>',
wrapper: 'efenudu (ọnégbáge)</br>ọscba <i><small>upper wrapper (of the two) worn by women</small></i></br>anikú (otéhú) <i><small>lower wrapper (of the two) worn by women</small></i></br>egbru <i><small>wrapper worn by men</small></i></br>ubuara <i><small>handwoven wrapper worn by elders</small></i>',
'old coin': 'áníní <i><small>originally a tenth of a penny</small></i>',
draughts: 'apene',
hornbill: 'ápiápiá',
knife: 'aphia',
'poisonous seed': 'areba',
'baby louse': 'arere',
'fishing net': 'árírí',
// aruérivwi n. designated spot where traditional rites are offered to the ancestors
mercy: 'aruẹdọ',
prophesy: 'aruẹmrẹ',
march: 'arhá <i><small>March</small></i>',
forehead: 'arhare (ekorhi)',
salvation: 'arhọ',
contribution: 'árhọ&#768ghọ',
development: 'árhuẹrẹ',
place: 'asa',
bird: 'asá <i><small>bird with red beak that bores hole in the pit</small></i>',
june: 'asán <i><small>June</small></i>',
abattoir: 'asadáveravwe',
acquittal: 'asé',
odd: 'asén',
everywhere: 'aseje',
mamba: 'ásiweri',
night: 'aso',
'it is said': 'atánẹ',
tray: 'atẹtẹ (akpata) <i><small>made locally from a plant called éti</small></i>',
'flat basin': 'atẹtẹ (akpata) <i><small>made locally from a plant called éti</small></i>',
'rumour monger': 'atikprere',
'chewing stick': 'ató',
savanna: 'aton',
february: 'avá <i><small>February</small></i>',
armpit: 'áviávwe (aviẹn)',
we: 'avwáre',
us: 'avwárẹn',
ponds: 'avware <i><small>wide area with collection of ponds</small></i>',
favourite: 'ávwebọ <i><small>e.g. wife</small></i>',
sweetness: 'avwerhe',
flag: 'avwiana',
wife: 'ávwiórọvwe <i><small>wife always treated with disdain by the husband</small></i></br>ayerúwevwi <i><small>housewife</small></i>',
rainbow: 'ávworo',
gill: 'avwré (ẹrọ)',
argument: 'avwro',
hour: 'awa',
ancient: 'aware',
hausa: 'áwúsá <i><small>Urhobo name for the Hausa people and their language</small></i>',
basket: 'ayarọ <i><small>basket used by women in fishing</small></i>',
'meet you well': 'ayávwa <i><small>meet you well (i.e. at table)</small></i>',
woman: 'aye',
they: 'ayen',
them: 'áyen',
Mrs: 'ayerórọvwe',
housewife: 'ayerúwevwi',
'pregnant woman': 'ayevevu',
'pressing iron': 'ayọni',
'public place': 'azagba (asotu)',
spirit: 'aziza <i><small>spirit roaming in the forest which gives rise to whirlwind</small></i>',

////////////////////////// Bb 
loose: 'bá <i><small>be loose (of a baby carried on the back)</small></i>',
never: 'bẹdẹ',
forever: 'bẹdẹbẹdẹ (rhirírín) <i><small>continuously (of time)</small></i>',
romance: 'bẹnẹ',
tear: 'bẹrẹ&#768',
until: 'bẹsiẹye',
push: 'bi (gere)',
grope: 'bibi',
'roam aimlessly': 'bibi',
black: 'biebí (obiebi)',
please: 'biko',
'make way for': 'bioma',
crow: 'bo',
swim: 'bo <i><small>of fish</small></i>',
build: 'bọ (tẹ)',
comfort: 'bọrọ',
warm: 'bọrọbọrọ (vwiọrọvwiọrọ)',
plentiful: 'bu',
plenty: 'bu',
awkward: 'búbú',
clumsy: 'búbú',
scrape: 'bue',
many: 'buebu',
'too many': 'búnọ',
much: 'búnọ',
bad: 'brabra',
'how many': 'bró',
'how much': 'bró',
cut: 'bru',
worry: 'brúdú <i><small>about/over something</small></i>',
advise: 'brúche',

/////////////////// Cc 
support: 'chá',
aid: 'chá',
screw: 'chavwọ',
cook: 'chere',
tread: 'chiyi <i><small>on something</small></i>',
steal: 'cho',
help: 'chúko',
///////////////////// Dd
drink: 'da',
sharp: 'dádá',
welcome: 'dede',
nevertheless: 'dédévwo',
buy: 'dẹ',
careful: 'dẹ&#768dẹ&#768',
block: 'di',
menstruate: 'dia',
what: 'dié',
'request one to say': 'diguẹ',
nearly: 'dino',
thank: 'do <i><small>general greeting which expresses variety of sentiments</small></i>',
throw: 'dó',
slack: 'doghodogho',
lean: 'dọdọn',
thin: 'dọdọn',
mate: 'du',
pound: 'duvwu',

///////////////// Dj dj
peppery: 'djádjá',
hide: 'djávwe (sínu)',
explain: 'djé',
show: 'djé',
spray: 'dje <i><small>somebody with medicine by mouth</small></i>',
run: 'djẹ',
'drive away': 'djẹ&#768 <i><small>animate objects</small></i>',
germinate: 'djẹ',
foolish: 'djídjí (ghẹghẹ)',
foolishly: 'djídjí',
introduce: 'djoma <i><small>oneself to</small></i>',
fan: 'dju',

////////////////////// Ee
yes: 'e <i><small>response to most greetings and directives</small></i>',
'sharp grass': 'ebẹ&#768n',
'native bag': 'ébo <i><small>woven native bag made of raffia palm</small></i>',
'act of crowing': 'ebó',
'thatch roof': 'ebọ&#768',
darkness: 'ébri (okuku), (eghó)',
'act of cutting': 'ebró',
cutting: 'ebró',
'bad omen': 'echa',
forgetfulness: 'echẹ&#768ro',
stealing: 'echó',
reception: 'edede',
welcome: 'edede',
patience: 'ediri',
noise: 'edo',
'door frame': 'edovi',
spider: 'edjákekete',
peer: 'edje',
explanation: 'édjé',
description: 'édjé',
crocodile: 'edjere',
tiger: 'edjenékpo (adjanákpu)',
wealth: 'efe',
bird: 'eferifẹn (ọ&#768vwra)',
// éfi1 n. fenced hidden place where masquerades and the like are dressed
rope: 'efi <i><small>used by palm collector in climbing the palm tree</small></i>',
hob: 'egaga',
glass: 'eganase <i><small>glass for drinking wine</small></i>',
bowel: 'égede',
'storey building': 'égenége (égedége)',
'act of pushing': 'egéré (ebió)',
pushing: 'egéré (ebió) <i><small>act of pushing<i><small>',
vomit: 'égérẹ&#768 (ẹkpá)',
kite: 'égodi (ógodi)',
compound: 'égodo (iyere)',
'pounded yam': 'egú',
jaw: 'égba (ọhwa)',
needle: 'egbedé1 (ukoti)',
injection: 'egbedé',
barrel: 'egbedi <i><small>barrel once used for storing commercial oil for export</small></i>',
preparation: 'egbémuó',
'forest jungle': 'égbó',
ram: 'egbo',
'bahama grass': 'egbrí',
west: 'eghanran (okún)',
'young man': 'éghene',
enmity: 'éghre',
elbow: 'éghróbọ',
ankle: 'éghrówọ',
knee: 'éghrúgbo',
funnel: 'éghwo (ághwo)',
massage: 'eghwóro',
moth: 'eghwọghwọ <i><small>clothes’ moth</small></i>',
chamelon: 'éghwughwẹ',
July: 'eghwrẹ&#768',
hoe: 'eghwro (ọguotọ)',
dance: 'éha (igbe)',
play: 'éha',
game: 'éha',
'white sand': 'éhapho',
umbrella: 'charha (achicha)',
fine: 'eho',
'hidden place': 'éhóhó',
waist: 'éhún',
bat: 'ehuhu',
coitus: 'ehware',
'sexual intercourse': 'ehware',
punishment: 'éhwé', 
beating: 'éhwé',
laughter: 'ehwẹ',
joke: 'ehwẹ&#768jẹ&#768 (ọ&#768dẹn)', 
jest: 'ehwẹ&#768jẹ&#768 (ọ&#768dẹn)',
swamp: 'éhwọrhọ',
praise: 'éjíro',
all: 'ejóbi (eje)',
every: 'ejóbi (eje)',
abuse: 'ékán (ẹ&#768hárhọ&#768)',
'act of counting': 'ekéré',
counting: 'ekéré',
market: 'eki',
'raffia palm': 'ékian (ọgọrọ)',
sitting: 'ékídia (étídia), (échídia)',
sewing: 'ekó',
area: 'ekogho',
ayo: 'ekọ&#768 <i><small>game with 12 holes played with 4 counters each in a hole</small></i>',
warri: 'ekọ&#768',
property: 'ekuakua',
togetherness: 'ékúgbé',
cold: 'ekpahe',
'fifty naira': 'ekpahọ uje gbẹ iyorin',
skull: 'ékpéhruyovwi',
shout: 'ékpérẹ&#768 (unuébo)',
exclamation: 'ékpérẹ&#768 (unuébo)',
box: 'ékpeti',
sand: 'ékpé (orhu)',
bag: 'ékpo (ékpu)', 
pocket: 'ékpo (ékpu)',
thigh: 'ékpóghówo',
'act of dragging': 'ekpono',
dragging: 'ekpono',
// ekrirhékrẹbe n. insect that builds a shelter of small pieces of wood round itself
family: 'ékru',
bundle: 'ekru',
// ema n. dance done mainly by elderly people with the upper part of the body exposed
// emare n. ground yam or plantain used for sacrifice
'act of plaiting': 'emé1 <i><small>act of plaiting hair</small></i>',
plaiting: 'emé1 <i><small>act of plaiting hair</small></i>',
twine: 'emé',
youth: 'éméghene',
gently: 'ememerha',
moon: 'éméravwe',
month: 'éméravwe',
little: 'émérha',
food: 'emu (emare)',
standing: 'émúdia',
solidarity: 'émúdiágá',
'act of carrying': 'emuó',
carrying: 'emuó <i><small>act of carrying</small></i>',
'act of arresting': 'emuó',
arresting: 'emuó <i><small>act of arresting</small></i>',
foodstuff: 'emuore',
'motorcycle': 'enákpukpu (imotosakoro)',
pineapple: 'enanadja',
elephant: 'eni',
'head pad': 'ení',
hippopotamus: 'eniáme (ẹ&#768rhẹ&#768n)',
'act of quitting': 'enó',
quitting: 'enó <i><small>act of quitting</small></i>',
brightness: 'énó',
up: 'énu (obénu)',
top: 'énu (obénu)',
'act of grumbling': 'enuebro',
grumbling: 'enuebro <i><small>act of grumbling</small></i>',
ascension: 'énuerá',
spittle: 'enya',
'half kobo': 'epini',
oracle: 'epha',
divination: 'epha',
uring: 'ephẹn',
ringworm: 'ephẹphẹ (ephẹren)',
language: 'éphẹ&#768rẹ',
Ijoh: 'éphẹ&#768rẹ',
Ijaw: 'éphẹ&#768rẹ',
'native blade': 'erákive (arẹn), (akive)',
dog: 'eráko',
// erán n. crushed palm kernel fibre for making fire
meat: 'eravwe',
animal: 'eravwe',
mat: 'eré <i><small>kind of mat</small></i>',
gain: 'erere',
fish: 'eri</br>ẹba <i><small>fish specie</small></i>',
knowledge: 'ériáriẹ',
'over feeding': 'eriávọ',
'land of the dead': 'erivwi',
backbiting: 'ero',
dove: 'érurẹ',
three: 'érha',
fire: 'erhare',
hell: 'erhare',
spice: 'érhe <i><small>kind of spice</small></i>',
yawn: 'érhe',
ceiling: 'erherin',
soul: 'erhi',
spirit: 'erhi',
butterfly: 'erhi',
'tale bearing': 'érhia (úgbéje)',
'alligator pepper': 'erhié',
ant: 'erhirhi (ómóraravwe)</br>ésákpa <i><small>ant specie</small></i></br>ivwri <i><small>ants that build their nest beneath the leaves</small></i></br>íyáwọ <i><small>soldier ant</small></i>',
millipede: 'erhívwi',
hat: 'erhu',
barn: 'erhún',
cow: 'erhuẹ&#768',
'act of bending': 'érhuẹ&#768',
bending: 'érhuẹ&#768 <i><small>act of bending</small></i>',
port: 'erhuru',
'refuse dump': 'erhurhu',
beauty: 'érhuvwu',
six: 'ésan',
bail: 'esábọ',
'great great grandchild': 'esákpógodi',
calling: 'esé',
reading: 'esé',
faith: 'esegbúyóta',
belief: 'esegbúyóta',
pig: 'esi',
sow: 'esiáye',
wirting: 'esió',
reduction: 'esiónó',
'bush pig': 'esirághwá',
base: 'esiri',
sack: 'esiso',
'two hundred naira': 'esiso',
treatment: 'esivwo',
contesting: 'esivwo',
'act of struggling for': 'esivwo',
struggling: 'omẹ&#768vwárhọ</br>esivwo <i><small>act of struggling for</small></i>',
redemption: 'esívwórhọ',
'grey hair': 'esha',
'act of falling': 'éshé',
falling: 'éshé <i><small>act of falling</small></i>',
failure: 'eshé',
rashes: 'eshẹ',
crawcraw: 'eshẹ',
devil: 'eshu',
ward: 'ete',
// éti n. plant used locally for making trays and other things
here: 'etinẹ',
there: 'etíyi',
watermelon: 'éto',
heap: 'etu',
bargain: 'evé',
breast: 'evie',
some: 'evo',
stomach: 'evun (úgáva)',
belly: 'evun (úgáva)',
pregnancy: 'evun',
in: 'evun <i><small>side</small></i>',
shop: 'évun',
store: 'évun',
diarrhoea: 'evuétué',
dysentery: 'evuétué',
abortion: 'evuẹ&#768kpárọ',
recognition: 'evúghe',
'act of reaping': 'evuó',
reaping: 'evuó <i><small>act of reaping</small></i>',
harvesting: 'evuó',
bank: 'évurígho (ibanki)',
roasting: 'evúvwó',
rising: 'evrẹ&#768',
resurrection: 'evrẹ&#768núshi',
dream: 'évwérhẹ',
birth: 'évwiẹ',
forgiveness: 'evwóghóvwo',
coronation: 'evwómuẹ',
'bat like animal': 'evwu',
somersault: 'evwré',
'palm oil': 'evwri (ọ&#768fígbo)',
'mineral oil': 'evwri (ọ&#768fígbo)',
dew: 'evwrú',
'bush clearing': 'éwán',
'palm branch': 'ewavwe <i><small>palm branch with leaves on</small></i>',
// ewé (eghwé) v.n. act of passing a thread through the eye of a needle, etc.
transfer: 'ewéne',
change: 'ewéne',
monkey: 'ewéri',
'express happiness': 'éwewu',
shirt: 'éwun',
trousers: 'éwunráwọ',
bet: 'eyá',
'guinea grass': 'éyareya',
dedication: 'ezekẹ',
///////////////////////////// Ẹ ẹ

nakedness: 'ẹban',
rag: 'ẹbamwá',
leaf: 'ẹbe',
lip: 'ẹbẹgbunu',
'love play': 'ẹbẹnẹ',
side: 'ẹ&#768bẹ&#768re',
piece: 'ẹbẹre',
opposite: 'ẹ&#768bẹ&#768rochékọ',
'lemon grass': 'ẹbiriẹ',
medicine: 'ẹbo',
construction: 'ẹbó',
door: 'échẹ',
'act of drinking': 'ẹdá',
drinking: 'ẹdá <i><small>act of drinking</small></i>',
'day before traditional market day': 'ẹdebi',
day: 'ẹdẹ',
'act of buying': 'ẹdẹ&#768',
buying: 'ẹdẹ&#768 <i><small>act of buying</small></i>',
'day after tomorrow': 'ẹdẹjerọ',
'market day': 'ẹdẹ&#768wọ <i><small>a day for abstaining from going to the bush for farming</small></i>',
residence: 'ẹdia',
place: 'ẹdia',
week: 'ẹdidjana',
sunday: 'ẹdidjanarode <i><small>Sunday</small></i>',
saturday: 'ẹdidjanarotete <i><small>Saturday</small></i>',
'traditional working day': 'ẹdiruo',
wednesday: 'ẹdiruorérhá <i><small>Wednesday</small></i>',
thusrday: 'ẹdiruorẹ&#768né <i><small>Thursday</small></i>',
monday: 'ẹdiruorẹ&#768sósuọ&#768 <i><small>Monday</small></i>',
tuesday: 'ẹdiruorívẹ&#768 <i><small>Tuesday</small></i>',
friday: 'ẹdiruoríyórín <i><small>Friday</small></i>',
leanness: 'ẹdọ',
// ẹdúhrẹ n. traditional day of abstaining from work and some other activities
'act of hiding': 'ẹdjávwọ (esióne)',
hiding: 'ẹdjávwọ (esióne) <i><small>act of hiding</small></i>',
'court case': 'ẹ&#768djọ&#768',
masquerade: 'ẹdjọ',
shrine: 'ẹdjọ',
translation: 'ẹfá',
feast: 'ẹfa <i><small>feast held by traditional worshippers</small></i>',
'region of the ribs': 'ẹfẹn',
juggling: 'ẹfrẹ&#768',
barren: 'ẹga',
service: 'ẹga',
'act of driving': 'ẹguá',
driving: 'ẹguá <i><small>act of driving</small></i>',
defilement: 'ẹgua',
conference: 'ẹguare',
meeting: 'ẹguare',
gathering: 'ẹguare',
love: 'ẹ&#768guọ&#768nọ',
strength: 'ẹ&#768gbá',
effort: 'ẹ&#768gbá',
'act of embracing': 'ẹgbánọ',
embracing: 'ẹgbánọ <i><small>act of embracing</small></i>',
coven: 'ẹ&#768gborhá',
'group of towns': 'ẹ&#768gbórho',
abomination: 'ẹgha',
// ẹgha2 n. resultant effect of committing a forbidden act
dividing: 'ẹghárọ <i><small>act of dividing</small></i>',
'majestic walk': 'ẹghọ&#768riẹ',
castration: 'ẹghwárọ',
// ẹ&#768ghweya n. totality of married women in a given place
mat: 'ẹghwẹ&#768re',
slap: 'ẹ&#768ghwiẹ (ghwiẹ)',
burn: 'torhẹ (ẹghwiẹ)',
slipperiness: 'ẹghwóriẹ',
'express agreement': 'ẹhẹn',
expansion: 'ẹhẹrẹ',
waiting: 'ẹhẹrhẹ <i><small>act of waiting</small></i>',
palm: 'ẹ&#768hẹ&#768rhóbọ',
sole: 'ẹ&#768hẹ&#768rhówọ',
nest: 'ẹho',
bath: 'ẹ&#768họ&#768',
baptism: 'ẹhọ&#768nímwémwun',
october: 'ẹhwé <i><small>October</small></i>',
no: 'ẹjo',
remembrance: 'ẹkaruvwiyọ',
rust: 'ẹ&#768kegba',
share: 'ẹ&#768kẹ',
portion: 'ẹ&#768kẹ',
camel: 'ẹ&#768kẹkẹtẹ',
however: 'ẹ&#768kẹ&#768vuọvo',
sourness: 'ẹkiọ',
group: 'ẹko',
planting: 'ẹkọ <i><small>act of planting</small></i>',
packing: 'ẹkuá <i><small>act of packing</small></i>',
// ẹkuedi (okedi) n. place where palm nut collectors process the nuts
country: 'ẹ&#768kuótọ',
fool: 'ẹkpa',
unripe: 'ẹkpa',
lifting: 'ẹkpárọ <i><small>act of lifting</small></i>',
postponement: 'ẹkpárọ',
answer: 'ẹkpávwiyo', 
reply: 'ẹkpávwiyo',
gratitude: 'ẹ&#768kpẹ&#768vwẹ&#768',
thanks: 'ẹ&#768kpẹ&#768vwẹ&#768',
swelling: 'ẹ&#768kpo',
measuring: 'ẹmá <i><small>act of measuring</small></i>',
moulding: 'ẹmá',
sweetness: 'ẹmiẹmiẹ',
production: 'ẹmọ&#768 <i><small>production of fruits</small></i>',
visitation: 'ẹmrẹ&#768',
seeing: 'ẹmrẹ&#768 <i><small>act of seeing</small></i>',
realisation: 'ẹmrẹ&#768vúghe',
four: 'ẹ&#768ne',
pacification: 'ẹnẹ&#768rhẹ <i><small>e.g. from crying</small></i>',
grinding: 'ẹbi <i><small>act of grinding</small></i>',
creeping: 'ẹrán',
eight: 'ẹréré',
admission: 'ẹreyọ',
acceptance: 'ẹreyọ',
levelling: 'ẹrẹ&#768',
tongue: 'ẹrẹvwe',
eating: 'ẹriọ&#768 <i><small>act of eating</small></i>',
eye: 'ẹro',
swallowing: 'ẹrọ&#768 <i><small>act of swallowing</small></i>',
civilisation: 'ẹruérhié',
hope: 'ẹruévwióvwíyọ',
supervision: 'ẹruévwóte',
prophesy: 'ẹruẹ&#768mrẹ&#768',
entry: 'ẹruọ&#768',
flying: 'ẹrhá',
leopard: 'ẹrha (akason)',
swimming: 'ẹrhẹrhẹ',
wrist: 'ẹ&#768rhóbọ',
dislocation: 'ẹrhóghra <i><small>of a bone in the body</small></i>',
leech: 'ẹrhorho',
prayer: 'ẹhrovwo',
shooting: 'ẹsá <i><small>act of shooting</small></i>',
selection: 'ẹsánọ',
gift: 'ẹ&#768se',
souvenir: 'ẹ&#768seróka',
later: 'ẹsiẹ&#768fa',
refusal: 'ẹsiọ&#768',
sale: 'ẹshẹ&#768',
crawling: 'ẹshọ&#768rọ (ekpono) <i><small>act of crawling</small></i>',
// ẹtá v.n. act of recovering what is used as collateral security
'pool of water': 'ẹtẹrhe',
hair: 'ẹto',
beard: 'ẹtoégba',
burning: 'ẹtórhẹ <i><small>act of burning</small></i>',
picking: 'ẹtọ&#768rọ <i><small>act of picking</small></i>',
'female pubic hair': 'ẹtuohoro',
'male pubic hair': 'ẹtuoshọ',
beginning: 'ẹtuọ&#768vwíyọ',
starting: 'ẹtuọ&#768vwíyọ',
alligator: 'ẹva (ọrhọ&#768n)',
butchery: 'ẹvá',
bending: 'ẹvẹ&#768 <i><small>act of bending</small></i>',
belching: 'ẹvẹ <i><small>act of belching</small></i>',
repetition: 'ẹvwáriẹ',
wrapping: 'ẹvwárọ <i><small>act of wrapping</small></i>',
goat: 'ẹvwé',
kolanut: 'ẹvwe',
eczema: 'ẹvwẹ&#768',
'native pot': 'ẹ&#768vwẹrẹ',
'she goat': 'ẹvwiáye',
fading: 'ẹvwóriẹ',
'baby vomit': 'ẹ&#768vwóriẹ',
swelling: 'ẹvwọ&#768 <i><small>act of swelling</small></i>',
'collateral security': 'ẹ&#768wa',
pass: 'ẹwá',
mind: 'ẹ&#768wẹ&#768n',
breath: 'ẹ&#768wẹ&#768n',
drying: 'ẹyá <i><small>act of drying</small></i>',
bitterness: 'ẹyarọ',
begging: 'ẹyarọ <i><small>act of begging</small></i>',
may: 'ẹyeórin <i><small>May</small></i>',
'struggling for balance': 'ẹyẹ&#768ghrẹ&#768',
staggering: 'ẹyẹ&#768ghrẹ&#768',

///////////////////////////// Ff
translate: 'fá',
confess: 'fa',
cane: 'fá',
whip: 'fa',
transport: 'fán',
'be rich': 'fe',
empty: 'fefe',
differ: 'fẹnẹ',
differentiate: 'fẹnẹ',
leak: 'fi',
split: 'fiá',
hiss: 'fiunu',
farewell: 'fobọrhe <i><small>you may return soon (farewell)</small></i>',
clean: 'fon',
necessary: 'fori',
silence: 'fọ (fotoyi)',
wash: 'hworhẹ</br>fọrhọ <i><small>clothes</small></i></br>fọrhọ <i><small>extract liquid from leaves through squeezing</small></i>',
quench: 'fu',
quiet: 'fuefú',
juggle: 'frẹ&#768',
snatch: 'fru',
////////////////////////////// Gg
serve: 'ga',
'hold baby': 'ga <i><small>hold baby in squatting position to ease its defecation and urination</small></i>',
firmly: 'gagán (gan)',
well: 'gagán (gan)',
'very high': 'gegerege',
'very thin': 'gẹ&#768ngẹ&#768n',
eager: 'gidigidi',
impatient: 'gidigidi',
'state of heat': 'gidigidi <i><small>describes state of flame or heat</small></i>',
stout: 'gidigba',
massive: 'gidigba',
'very tall': 'gogorogo',
high: 'gogorogo',
worship: 'gọ',
judge: 'gu',
drive: 'gua (djẹ)',
frighten: 'gué (guegue)',
bent: 'gugunu',
dissolve: 'guọ',
destroy: 'guọghọ',
sluggish: 'guoguo',
weak: 'guoguo',
find: 'guọnọ',
'look for': 'guọnọ',
love: 'guọnọ',
want: 'guọnọ',
long: 'grogró',
tall: 'grogró (ogrogro)',

//////////////////////////////// GB gb
tie: 'gbá',
embrace: 'gbane',
dance: 'gbe (ópiri)',
narrate: 'gbe',
dirty: 'gbegbé',
underline: 'gberi',
rule: 'gberi',
continue: 'gberuo <i><small>please continue with your meal (sing.)</small></i>',
'cut grass': 'gbẹ',
smell: 'gbọn',
rotten: 'gbogbó',
'very long': 'gbọgbọrọgbọn',
'very tall': 'gbọgbọrọgbọn',
'very huge': 'gbọgbọrọgbọn', 
'shake something': 'gbrogho <i><small>shake something like a tin of oil</small></i>',
shock: 'gbrugho',

////////////////////////////// GH gh
forbid: 'gha',
dear: 'ghagháre', 
costly: 'ghagháre',
expensive: 'ghagháre',
divide: 'ghare',
expansive: 'gheregbe',
ordinary: 'ghevweghe',
'hoot at': 'gho',
hawk: 'ghoro',
entertain: 'ghọ',
'walk majestically': 'ghọriẹ',
// ghrẹghrẹ v.t call someone's name poetically to make it more appealing
transparent: 'ghroghro',

//////////////////////// GHW ghw
'carry': 'ghwa',
'take along': 'ghwa',
old: 'ghwaghwó',
castrate: 'ghware',
pack: 'ghwẹ <i><small>things</small></i></br>kua <i><small>property</small></i>',
announce: 'ghwoghwo',
slippery: 'ghworiẹ',
massage: 'ghworo',
rub: 'ghworo',
'be angry': 'ghwọ',
waste: 'ghwọrọ',
die: 'ghwu',


///////////////////// Hh
'have fun': 'ha <i><small>see also play</small></i>',
abuse: 'harhe',
'expression': 'héhé (ho) <i><small>express surprise</small></i></br>hweké <i><small>expresses surprise resulting from fear</small></i></br>í <i><small>expresses sad feelings</small></i></br>ghwo <i><small>exclamation of disappointment/surprise</small></i></br>Shuo! <i><small>expresses surprise</small></i>',
wide: 'hẹhẹre',
wait: 'hẹrhẹ',
fine: 'ho',
bathe: 'họ',
similar: 'họhọ',
close: 'huhu',
shut: 'huhu',
disorganise: 'hra',
scatter: 'hra',
'very dry': 'hrahrahra',

////////////////////// HW hw
pay: 'hwa',
tighten: 'hwá',
narrow: 'hwahwa',
kill: 'hwe',
break: 'hwe <i><small>of glass, bottles, etc</small></i>',
punish: 'hwé',
sweep: 'hwerhe',
laugh: 'hwẹ',
'very clean': 'hwrẹhwrẹhwrẹ',

////////////////////////// Ii
father: 'ọ&#768sẹ (ibába)',
'grand father': 'ibábode',
hunting: 'ibefí',
'maternity home': 'ibẹtẹni',
alphabet: 'íbietá',
'red poplin': 'ibósu (abósu)',
'mosquito net': 'ibọkpọ',
skirt: 'ibunúku',
'tribal marks': 'íbrébru (eka), (ila)',
mud: 'íbrehe',
second: 'rívẹ&#768</br> ibrẹro <i><small>of time</small></i>',
'five kobo': 'ichíbẹ',
'footprint': 'ichiyi',
// idónọ n. word used in reference to money mostly in the olden days
cupboard: 'idọrọ',
cocoyam: 'ídu',
'kerosene tin': 'idjagodo',
mumps: 'idjáhróhró',
// idjé n. game played by young girls in which they clap hands and jump
example: 'ídjédje',
road: 'idjérhe',
bicycle: 'idjíghere',
horn: 'idjo (ighóró), (ọgban)',
raffle: 'idjogbá', 
gambling: 'idjogbá',
'roman catholic father': 'ifada',
scorn: 'ifiaro',
'because of': 'ífikirẹ&#768',
// ifio (oghwa) n. money or material given to a person in appreciation of a good performance (e.g. during dancing)
// ifo n. work or something done in return for the same gesture
picture: 'ifotó',
waterleaf: 'ifọ&#768',
shoulder: 'igábọ (ákoko)',
garri: 'igarí',
'indian hemp': 'igé',
drum: 'igede',
timber: 'igedú',
triangle: 'ígógérha',
square: 'ígógẹ&#768ne',
angle: 'ígógó',
bucket: 'igogono (ikoroba)',
governor: 'igóvinẹ',
gossip: 'íguégu',
'Urhobo traditional religion': 'igbe',
prostitute: 'igberadja (ónóshọ&#768họ)',
eyebrow: 'ígbẹro',
wall: 'igbẹ&#768yi (igbẹ&#768hẹn), (omaruwevwi)',
igbo: 'igbo <i><small>Urhobo name for the Igbo people and their language</small></i>',
'armed robber': 'igbunegbú',
mystery: 'igbunu',
money: 'ígho',
'milk teeth': 'ígho',
'transport fare': 'íghorofán',
seven: 'íghwrẹ&#768',
ten: 'íhwe',
sixteen: 'íhwegbẹ ésan',
eighteen: 'íhwe gbẹ ẹ&#768rere',
seventeen: 'íhwegbẹ íghwrẹ&#768',
nineteen: 'íhwegbẹ írhirin',
thirteen: 'íhwérhá (íhwegbẹérha)',
fourteen: 'íhwẹ&#768né (íhwegbẹéne)',
fifteen: 'íhwiórí (íhwegbẹíyorin)',
twelve: 'íhwívẹ&#768 (íhwegbẹívẹ)',
covenant: 'íjí',
candle: 'ikadoro',
buttocks: 'ikebe',
'hide and seek': 'ikenekene',
'stilt dance': 'íkeníke',
cocoa: 'ikoko',
mattress: 'ikonosha',
cloud: 'íkoro (idadeghe)',
bangle: 'íkoro <i><small>bangle made of elephant tusks</small></i>',
stammer: 'ikọkọ',
crayfish: 'íku',
story: 'íkun',
drum: 'ikurú',
towel: 'ikpachá',
soyabeans: 'íkpákpáne',
zinc: 'ikpámáku',
shelf: 'ikpekpa',
melon: 'ikpógri',
duck: 'ikpukpuyẹkẹ',
kerosene: 'ikrasi',
trillion: 'íma <i><small>1,000,000,000,000</small></i>',
mango: 'imágoro',
mermaid: 'imamiwọta',
machine: 'imashini',
table: 'imẹ&#768jẹ (eméjé), (ikpekparọre)',
desk: 'imẹ&#768jẹrọ&#768ghwrọrọ (emẹ&#768jẹrọghwrọrọ)',
cassava: 'imidaka (eraka)',
minute: 'iminiti <i><small>of time</small></i>',
termite: 'ímíphopho',
excommunication: 'ímu',
assurance: 'ímuẹró',
cattle: 'ináma (imelu)',
pigeon: 'inékuku',
file: 'inémẹ (igbefia)',
mother: "óni</br>inéne <i><small>one's mother</small></i>",
grandmother: 'inénode',
today: 'inónẹ',
dirt: 'ínú',
pot: 'ipọ&#768to (itáson)<i><small>imported</small></i>',
button: 'ipọtọ&#768',
beans: 'íre (esha) <i><small>white</small></i></br>ísha <i><small>brown</small></i>',
radio: 'iredio (agboro)',
'rubber tree': 'iróba',
rubber: 'iróba',
thought: 'iroro',
rice: 'irósu',
activity: 'íruéru',
job: 'íruo',
handiwork: 'íruobọ',
'manual work': 'íruorugbóbọ',
presence: 'irháro',
pepper: 'irhíbo (isíbo)',
nine: 'írhirin',
itsekiri: 'írhóbo <i><small>Urhobo name for the Itsekiri people and their language</small></i>',
liver: 'irhue',
'mode of dressing': 'irhuó',
shoe: 'isabato',
sardine: 'isáma',
saw: 'isara',
camwood: 'iséné',
amen: 'isẹ',
proverb: 'isẹ&#768',
East: 'isí',
cigarette: 'isigáti',
star: 'ísio',
'foreign land': 'isiórho',
// isírógbo n. special bed designed for a bride on circumcision
soldier: 'isódje (isoja)',
excreta: 'ísọ',
stool: 'ísọ',
faeces: 'ísọ',
administration: 'ísuésu',
cardigan: 'isuéta',
'black pepper': 'ísháshá',
'ten kobo': 'ishéne (ushéne)',
'one naira': 'ishéne íhwe',
'fifty kobo': 'ishéne íyorin',
bedbugs: 'ishuáwúsá',
tobacco: 'ítába',
'water lettuce': 'itetebe',
'parable like statement': 'itẹ&#768',
television: 'telẹvishọn (ekpetiughe)',
blanket: 'itiani',
// itiró n. black eyeliner substance used by women as cosmetic on the eyes
tomato: 'itomátosi',
turkey: 'itonotono (itatono)',
torch: 'itọshi', 
mushroom: 'itú',
fungus: 'itutu',
promise: 'ívévé',
two: 'ívẹ',
guarantor: 'iviẹwa',
annoyance: 'ivuémióvwó',
smoke: 'ívwirhi',
bud: 'ivwo',
stream: 'ívwori',
tapioca: 'ivworhíya',
foam: 'ivwughẹ',
fat: 'ivwri',
scrotum: 'ivwríte',
ash: 'íwurhie',
gum: 'íyáko <i><small>teeth</small></i>',
sacrifice: 'íye',
// iye2 excl. word for appreciating an ideal situation
horse: 'iyési',
news: 'iyẹnrẹn',
gospel: 'iyẹ&#768siri',
curse: 'iyori',
oath: 'iyori',
five: 'íyorin',
strawberry: 'izẹn',
counterfeit: 'izẹbu <i><small>money</small></i>',
offering: 'izóbo',

////////////////////////// Jj
choose: 'jẹ',
let: 'jẹ&#768',
speak: 'jẹ',
yet: 'jẹ&#768',
send: 'ji',
praise: 'jiro',
unless: 'jokpa nẹ',
almost: 'joma',
'be careful': 'jomaótọ',
carefully: 'jomaótọ',
'leave off': 'jovwo',

/////////////////////////// Kk
// kada exp. response of kings and chiefs to the greetings and praise-singing of their subjects
'at all': 'kákán (phiéphié)',
lock: 'kare',
scratch: 'kare',
remember: 'karovwiyọ',
anywhere: 'kasakasa',
count: 'kere',
listen: 'kerhọ',
give: 'ke',
everyday: 'kẹdẹkẹdẹ',
daily: 'kẹdẹkẹdẹ',
'till another day': 'kẹ&#768dọ&#768fa',
goodbye: 'kẹ&#768dọ&#768fa',
precise: 'kẹkẹrẹkẹ', 
'required amount': 'kẹkẹrẹkẹ',
near: 'kẹrẹ&#768',
next: 'kẹrẹ&#768',
by: 'kẹrẹ&#768',
'till another time': 'kẹ&#768siẹ&#768fa <i><small>goodbye</small></i>',
before: 'kẹsiéye (távwe)',
sit: 'kidia (tidia), (chidia)',
'what else': 'kídié',
as: 'kírẹ&#768', 
like: 'kírẹ&#768',
sew: 'ko',
'till tomorrow': 'kódẹ (tódẹ)',
goodnight: 'kódẹ (tódẹ)',
'all kinds': 'kokakoka',
'any kind': 'kokakoka',
together: 'koko',
deep: 'kokódo',
deeply: 'kokódo',
tight: 'kókórókó <i><small>firmly</small></i>',
anybody: 'kohwokohwo',
anything: 'kóravwọkóravwọ',
'every town': 'korhokorho',
'every word': 'kotakota',
plant: 'kọ',
always: 'kọkekọke',
anytime: 'kọkekọke',
pluck: 'kọre',
pour: 'ku',
'depreciate in value': 'kueki',
fence: 'kuere (muogba), (ógba)',
and: 'kugbẹ&#768',
unite: 'kuomagbe',
'piece meal': 'krẹ&#768nkrén',
'keep long': 'kri',
assemble: 'kru <i><small>of things</small></i>',
/////////////////////// KP kp
vomit: 'kpa (geri)',
about: 'kpahe (kpa)',
on: 'kpahe (kpa)',
lift: 'kpare',
postpone: 'kpare',
quickly: 'kpatakpata',
answer: 'kpavwiyọ',
reply: 'kpavwiyọ',
knit: 'kpé',
high: 'kpénu',
shout: 'kperi (bunu)',
peel: 'kpẹn',
'till dawn': 'kpẹkpẹrẹkpẹ <i><small>staying awake</small></i>',
shallow: 'kpẹkpẹvwiẹ',
'be grateful to': 'kpẹvwẹ',
fold: 'kpirhi',
shake: 'kpogho',
worry: 'kpokpo (naghe) <i><small>trouble</small></i>',
fresh: 'kpókpọ',
new: 'kpókpọ',
drag: 'kpono',
crawl: 'kpono2 (shọrọ)',
low: 'kpótọ',
deflect: 'kpọ&#768',
dry: 'kpọ',
lumpy: 'kpọnọkpọnọ',
'make wet': 'kpọrhọ',
unexpectedly: 'kprégédé',
suddenly: 'kprégédé',

//////////////////////////////// M m
measure: 'má',
mould: 'ma',
well: 'mamọ',
writhe: 'manọ',
especially: 'marho',
particularly: 'marho', 
how: 'mavọ&#768',
plait: 'me',
pretend: 'meru',
feign: 'meru',
mine: 'mẹ&#768',
my: 'mẹ&#768',
i: 'mí (mé) <i><small>I</small></i>',
squeeze: 'mi',
take: 'mie',
sweet: 'miẹmiẹ',
greet: 'míguẹ <i><small>I am on my knees (greeting from a junior person to a senior or more elderly one)</small></i></br>misiẹguare <i><small>I greet the gathering (before and after making a speech)</small></i>',
ugly: 'miomiovwi',
spoil: 'miovwi',
borrow: 'momo',
produce: 'mọ',
carry: 'mu',
arrest: 'mu',
afflicted: 'mu <i><small>e.g. by sickness or disease</small></i>',
stand: 'mudia',
prepare: 'muegbe',
'get': 'muegbe',
ready: 'muegbe',
'give name': 'muodẹ',
see: 'mrẹ',
realise: 'mrẹvughe',
'find time': 'mrobọ (mruvwẹ)',
'get a chance to': 'mrobọ (mruvwẹ)',
press: 'mwa <i><small>of fruit</small></i>',

//////////////////////////////// Nn (LI)
the : 'na',
properly: 'nabe',
'this': 'nana',
these: 'nana',
now: 'nánánáná', 
'just now': 'nánánáná',
excrete: 'ne',
'pass out faeces': 'ne',
follow: 'nené',
from: 'nẹ',
pacify: 'nẹrhẹ',
look: 'ni',
shine: 'no',
ask: 'nọ',
grind: 'nọ&#768',
sharpen: 'nọ&#768',
drip: 'nọ&#768nọ&#768',
'pour a drop at a time': 'nọ&#768nọ&#768',
soft: 'nọnọ',
greasy: 'nọnọnọ',
oily: 'nọnọnọ',
open: 'nuvie <i><small>locked object only</small></i>',
///////////////////////////////// NY ny
'to use cutlass on': 'nyavwe',
press: 'nyẹ',
hear: 'nyo',

////////////////////////////// Oo
end: 'óba',
front: 'obáro (aro)',
forward: 'obáro (aro)',
basket: 'obere',
what: 'obo',
'left hand': 'obóhwẹre (obágobọ)',
'this side': 'obónẹ',
here: 'obónẹ',
under: 'obótọ (ótọ)',
'that side': 'obóyi',
there: 'obóyi',
hand: 'obọ',
recently: 'obọ',
intact: 'obọde',
'right hand': 'obọ&#768rhe',
// obọúnu exp. I am at table
once: 'obọvo (ẹsiẹvo)',
back: 'obúko',
behind: 'obúko',
adviser: 'obruche',
wedge: 'ochá',
blow: 'oché (ẹtéyọ)',
cook: 'ocheremu',
'water pot': 'ochẹ',
eunuch: 'óchíbẹ',
cutlass: 'oda (ágáda)</br>odjigbẹ <i><small>long slender cutlass used for grass cutting</small></i>',
matchete: 'oda (ágáda)',
naming: 'odemuo <i><small>name-giving</small></i>',
name: 'odẹ',
tomorrow: 'ódẹ',
yesterday: 'ódẹrọ&#768warena (ódẹrókporina)',
deaf: 'ódi',
mute: 'ódi',
grass: 'odi',
even: 'odín',
servant: 'odibo',
banana: 'ódíbó',
zero: 'odiodi',
nought: 'odiodi',
nothing: 'odiodi',
fever: 'odo',
'big mortar': 'ódó',
flower: 'ódódó',
nickname: 'odóvá',
'one hundred thousand': 'odú <i><small>100,000</small></i>',
billion: 'odúduíma <i><small>1000,000,000</small></i>',
million: 'odúdúrú <i><small>1,000,000</small></i>',
goldsmith: 'oduvwiro',
soap: 'odja',
'hook worm': 'ódjan',
pain: 'ódjádja',
secret: 'odjávwọ',
exhibition: 'odjephia',
introduction: 'omédje</br>odjephia <i><small>e.g. as part of a book</small></i>',
cold: 'odjidjiro <i><small>in some contexts as</small></i> djidjiro',
'yellow bush yam': 'odjigbẹ',
'mat made of raffia palm': 'odjiko',
wind: 'odju (avwẹrẹ), (aphopho)',
air: 'odju (avwẹrẹ), (aphopho)',
heaven: 'odjúvwú',
transport: 'ofán',
'yam beetle': 'ófe',
tuberculosis: 'ófe',
difference: 'ofẹ&#768nẹ',
smallpox: 'ofi',
lie: 'ofiá</br>sherhẹ <i><small>to lay down</small></i>',
war: 'ofovwi',
power: 'ógága',
dish: 'ogebene',
pimple: 'ógẹ',
'stormy rain': 'ogiribo',
sheep: 'ogodẹ',
frog: 'ogoro</br>okere <i><small>frog specie</small></i>',
robin: 'ogue',
liar: 'oguefia (ovwọrefia)',
iron: 'ogbá',
quarter: 'ógbe',
poverty: 'ogbere',
tortoise: 'ogbeyin (arirhiri)',
eel: 'ógbẹnẹ',
python: 'ógbo',
distance: 'ogbóko',
'monitor lizard': 'ógborígbo (ọwọrhọn)',
iguana: 'ógborígbo (ọwọrhọn)',
cock: 'ogborhuane (okokoroko)',
'tree felling': 'ogbọ <i><small>in the preparation of farm land</small></i>',
bullet: 'ogbọnọ',
warrior: 'ogbú',
// ogha (ogaga) n. long instrument with barbs used for killing fish (e.g. spear)
division: 'oghare',
afternoon: 'oghẹrúvo',
lizard: 'óghóghori',
hawker: 'oghoremu',
branch: 'oghọ',
hook: 'oghọre',
mouse: 'oghresi',
tree: 'oghriki <i><small>tree specie</small></i></br>ohahe <i><small>silk-cotton tree</small></i></br>okpagha <i><small>oil-bean tree</small></i>',
load: 'oghwá',
stall: 'óghwa',
'castrated animal': 'oghwara <i><small>e.g. pig</small></i>',
gourd: 'oghwara',
'oil soap': 'oghwévwri (oghwọ&#768fígbo)',
soup: 'oghwó (irhibo)</br>amiédi (oghwórédi) <i><small>banga soup</small></i>',
toad: 'oghwókpo',
mockery: 'oha',
heat: 'oheri',
width: 'óhẹ&#768hẹre',
worm: 'ohori',
vagina: 'óhoró',
neck: 'ohọre',
fight: 'ohọnre',
skin: 'óhọ&#768rọ',
disorganisation: 'óhra',
rat: 'ohro (erawevwi)',
harmattan: 'ohwahwa',
ghost: 'ohwérivwi',
fisherman: 'ohwiyeri',
person: 'ohwó',
'each other': 'ohwóhwó',
'human being': 'ohwórákpọ',
suffering: 'oja',
'yam stick': 'ojá',
thief: 'oji',
chain: 'ojọrọ',
type: 'oka',
kind: 'oka',
mark: 'óka',
crop: 'ókákọ',
masquerade: 'ókao',
'birth mark': 'ókarerivwi',
'gun shot': 'okárọ',
wardrobe: 'okárọ',
yoruba: 'oke <i><small>Urhobo name for the Yoruba people and their language</small></i>',
tailor: 'okemwa',
chairman: 'okidiagbara (ochidiagbara)',
friend: 'óko (ugbeya), (ọsẹ)',
asset: 'okọ&#768',
boat: 'okọ',
canoe: 'okọ',
// okọrédi n. boat used locally for production of palm oil
aeroplane: 'okọrénu (ẹrupleni)',
ship: 'okọrérháre (okuna)',
coffin: 'okọrórivwi (ékpetiórivwi)',
motor: 'okọrótọ (imóto)',
'motor vehicle': 'okọrótọ (imóto)',
raft: 'okọrúhọphe',
necessity: 'okuba',
federal: 'okugbé',
togetherness: 'okugbé',
owl: 'okukuji (okpurhukpurhu)',
headtie: 'okuogho (uriọfọ), (onẹso), (ọvwauyovwi)',
headscarf: 'okuogho (uriọfọ), (onẹso), (ọvwauyovwi)',
calabash: 'okpa',
// ókpa2 n. hand-woven wrapper as thick as blanket
'two naira': 'okpahọvo',
haste: 'okpakpa',
'big hawk': 'okpému',
'strange thing': 'okpému',
extraordinary: 'okpému',
trouble: 'okpetú (ógbarógba)',
lion: 'okpohrókpo',
shortness: 'ókrẹkrẹ',
'he goat': 'okri (ẹkpro)',
body: 'oma (ugboma)',
self: 'oma (ugboma)',
image: 'óma',
'how are you': 'omagáre',
myself: 'omamẹ',
fruit: 'omámọ',
best: 'omamọ (uvi)',
special: 'omamọ (uvi)',
oneself: 'omaohwó',
ourselves: 'omarávwáre',
themselves: 'omaráyen',
yourselves: 'omarowan (omarovwan)',
herself: 'omarọ&#768yen',
himself: 'omarọ&#768yen',
itself: 'omarọ&#768yen',
pleasure: 'omavwerhovwẹ', 
joy: 'omavwerhovwẹ',
yourself: 'omawẹn',
unity: 'omékuogbe',
holiday: 'omérovwo',
pretence: 'omeru',
pomposity: 'omévwuo',
protection: 'omẹ&#768cha',
harshness: 'omẹ&#768dja',
jealousy: 'omẹ&#768riọ',
shame: 'omẹ&#768vuọ',
competition: 'omẹ&#768vwávwọ',
disgrace: 'omẹ&#768vwọvwọ (ovwọvwọvwe)',
mister: 'omíragua <i><small>Mr.</small></i>',
lamb: 'ómógodẹ',
parrot: 'ómoko',
'young he goat': 'ómókri (ẹ&#768mẹ&#768kpro)',
relation: 'ómóni',
infant: 'ómótete',
plate: 'ómozé <i><small>unbreakable</small></i></br>ọséte <i><small>breakable</small></i>',
'arbitrary act': 'omurú',
skill: 'oná',
question: 'ónánọ&#768 (onọ)',
race: 'ónẹ',
stepmother: 'óniáruakpọ',
'in law': 'óniáye <i><small>female</small></i></br>ọ&#768gọ <i><small>male</small></i></br>óniorọvwe <i><small>mother/sister in-law</small></i>',
master: 'onini',
brother: 'óniọvo',
sister: 'óniọvo',
programme: 'oniru',
syllabus: 'oniyono',
who: 'óno',
cat: 'ónógbo',
'sea god': 'ólókú',
leader: 'onorí',
chief: 'ólórógun',
commissioner: 'onótu',
minister: 'onótu',
spectator: 'onughe',
face: 'opháro',
whistle: 'óphiọrọ',
'pepper soup': 'óphopho (irhiberhare)',
mudfish: 'óphọrọ</br>úbieri <i><small>mudfish specie</small></i>',
sore: 'ora',
'stomach ulcer': 'oraévun',
bracelet: 'óraóbọ',
necklace: 'óraóhọre',
thing: 'órávwọ',
something: 'órávwọ',
hare: 'orere',
feast: 'orẹ',
plea: 'órẹ',
sight: 'orẹ&#768mrẹ&#768',
pomade: 'orí',
// óri n. food made of corn
pus: 'orin',
August: 'oriaren',
'palm tree': 'óriẹ&#768',
corpse: 'orivwi',
funeral: 'orivwiéshó',
gold: 'óro',
wasp: 'oró',
accountant: 'ororigho',
marriage: 'orọvwe',
'extended family': 'órua',
crime: 'oruchọ&#768',
completion: 'orugbá',
revenge: 'orukérí',
'co operation': 'orukugbé',
corruption: 'orukuruku',
sinner: 'orumwemwu',
thread: 'orúrú',
witchcraft: 'órhá',
well: 'orhare',
midwife: 'órhére',
reverend: 'orhérẹn <i><small>Rev.</small></i>',
cricket: 'orhérhé',
abdomen: 'orhẹ',
verdict: 'orhiẹ&#768',
'electric fish': 'orhirhi',
town: 'orho (órere)',
surrounding: 'órhóma',
ear: 'órhọ&#768',
deer: 'órhua',
madness: 'orhuẹ',
hunter: 'orhuẹ&#7682',
'catfish': 'orhuẹre',
'blind person': 'órhuẹ&#768ro',
debt: 'osa',
salary: 'osa',
// ósáye n. payment made as compensation for defiling another man's wife
deposit: 'osébro',
contest: 'oseghe',
witness: 'óseri',
scale: 'ósẹ&#768',
// osẹ&#768vwe (eheri) n. fashionably dressed for an occasion
stroke: 'osi',
secretary: 'osiẹbe',
rain: 'osio',
spider: 'osioruru (álẹ)',
saviour: 'osivwohwo',
anguish: 'osọnọ',
shepherd: 'osuigodẹ',
oppression: 'oshenyẹ&#768',
penis: 'óshọ&#768',
fear: 'oshọ',
ouse: 'oshu',
speech: 'otá',
word: 'otá',
outside: 'ótáfe (uphẹphẹ)',
poem: 'otáríroro',
tumbler: 'otebene (égo)',
small: 'ótete',
leprosy: 'otí (irigbẹyi)',
ground: 'ótọ',
down: 'ótọ',
meaning: 'ótọ',
longevity: 'otọ&#768vwe',
majority: 'otu',
'group of people': 'otu',
scolding: 'óva',
'window': 'ovákpó',
king: 'ovie', 
'traditional ruler': 'ovie',
queen: 'ovieraye',
cry: 'óviẹ&#768',
message: 'óvuẹ',
plank: 'ovwavwa',
sleep: 'ovwerhẹ',
measles: 'ovwi',
shade: 'óvwie',
'poor person': 'ovwiégbére',
leather: 'ovwiẹ&#7681',
clay: 'ovwiẹ&#768n',
laziness: 'ovwiẹrẹ',
deceit: 'ovwiẹ&#768vwe',
south: 'ovwoọ&#768',
evening: 'óvwọvwọ',
anger: 'ovwu',
'co wife': 'óvwrovwro',
'August break': 'ówáre <i><small>brief period of sunshine in the rainy season</small></i>',
mosquito: 'ówe',
'bush mango': 'owe',
fishpond: 'owẹ',
hunger: 'owẹvwe',
work: 'ówia',
catarrh: 'ówórhi',
leg: 'owọ',
cough: 'ówọrhe',
walk: 'óyan',
movement: 'óyan',
'garden egg': 'oyao',
begging: 'oyare',
circumcision: 'oyavwe',
'white man': 'óyibó',
mulatto: 'óyibótọ (obobo)',
albino: 'óyibótọ (obobo)',
boldness: 'oyivwi',
rudeness: 'oyivwi (aruéyivwo)',
okay: 'oyóma',
good: 'oyóma',
teacher: 'oyono',
professor: 'oyonorode',
beautiful: 'oyoyovwi (yoyovwi)',
sugar: 'oyubu',
basin: 'ozé',
murderer: 'ózighẹ&#768',
roughness: 'ozighi',
'trouble making': 'ozighi',

///////////////////////////////// Ọ ọ
he: 'ọ',
she: 'ọ',
it: 'ọ',
blood: 'ọbara',
book: 'ọbe',
newspaper: 'ọberíyẹnrẹn',
letter: 'ọberóvuẹ</br>ubiota <i><small>a, b, c, etc.</small></i>',
dictionary: 'ọberọ&#768feta',
calendar: 'ọberúkeri',
certificate: 'ọberúseri',
receipt: 'ọberúseri',
// ọbẹrokpa n. palm nuts collector
doctor: 'ọbo <i><small>medical/traditional</small></i></br>ọboériáriẹ <i><small>academic</small></i>',
'young thing': 'ọbóba',
offspring: 'ọbóba',
young: 'ọbóba',
tender: 'ọbóba',
'oracle man': 'ọboepha',
pharmacist: 'ọboimwu (ọboihuvwu)',
singer: 'ọ&#768boine',
architect: 'ọbuwevwi',
hip: 'ọchọ&#768',
helper: 'ọchuko',
pillow: 'ọchuyovwi',
paint: 'ọda',
'rich person': 'ọdafe',
interest: 'ọdávwẹ',
desire: 'ọdávwẹ',
examination: 'ọdavwiní',
temptation: 'ọdavwiní',
customer: 'ọdemu',
'larvae of beetle': 'ọ&#768dọ',
sweat: 'ọdja',
another: 'ọ&#768fa',
fornication: 'ọfarhiẹ',
translator: 'ọfeta',
tilapia: 'ọfẹ&#768',
comb: 'ọfẹto',
tick: 'ọ&#768fo',
white: 'ọfuanfo (fuanfo)',
disease: 'ọga (emiavwe)',
sickness: 'ọga (emiavwe)',
sir: 'ọgá',
boss: 'ọgá',
'animal track': 'ọgán (ogẹ&#768n)',
crab: 'ọgadiẹ',
tough: 'ọgagan (gagan)',
strong: 'ọgagan (gagan)',
hard: 'ọgagan (gagan)',
diabetics: 'ọgarephẹn',
'idol worshipper': 'ọgẹdjọ',
ladle: 'ọgẹrobọ (urárá)',
bottle: 'ọgọ&#768',
pit: 'ọgọdọ',
christian: 'ọgọghẹnẹ <i><small>Christian</small></i>',
palace: 'ọguá',
'town hall': 'ọguá',
driver: 'ọguimoto',
hero: 'ọ&#768gbá',
thirty: 'ọ&#768gban',
glutton: 'ọ&#768gbọ&#768re',
drunkard: 'ọ&#768gbúdi',
dear: 'ọ&#768ghágháre',
precious: 'ọ&#768ghágháre',
god: 'Óghẹnẹ&#768 (osonobrughwẹ) <i><small>God</small></i>',
respect: 'ọghọ',
honour: 'ọghọ',
virginity: 'ọghọ',
'elephant grass': 'ọghọrọgbọdọ',
centipede: 'ọghrẹrẹ',
cheating: 'ọghware',
reporter: 'ọghweta',
gathering: 'ọghwẹ&#768koko',
farmer: 'ọghwẹ&#768rẹ',
'old age': 'ọghwo',
waste: 'ọghwọrọ',
slope: 'ọghwrọrọ',
gecko: 'ọhẹrhuwevwi',
bushfowl: 'ọhohowa (ọhọaghwa)',
fowl: 'ọ&#768họ',
sense: 'ọhọ&#768',
hen: 'ọ&#768họáye',
heavy: 'ọhọhọhọ (họhọhọ)',
'chieftaincy title': 'ọhọvwọre',
shrew: 'ọ&#768hróware',
'dung beetle': 'ọhwarhisọ',
tadpole: 'ọhwẹre (igbrigbririn)',
'eye pain': 'ọhwẹre <i><small>Apollo</small></i>',
'left handed': 'ọ&#768hwẹróbọ', 
'left handed person': 'ọ&#768hwẹróbọ',
gun: 'ọ&#768hwúnu',
toothache: 'ọja',
disrespect: 'ọjẹfia',
corn: 'ọ&#768ka',
maize: 'ọ&#768ka',
sunbird: 'ọkán',
'chieftaincy title': 'ọkakúro',
// ọkaórho n. title normally given to the oldest man in a town
woodpecker: 'ọkarekọ',
time: 'ọke',
miserliness: 'ọké (okpẹ&#768)',
occasionally: 'ọkefiọke',
kingfisher: 'ọkeghọrọ',
when: 'ọkevọ&#768',
tide: 'ọkẹre',
flood: 'ọkẹre',
birthday: 'ọkiévwiẹ',
'harvest season': 'ọkiorhọ <i><small>yams, crops, etc</small></i>',
'rainy season': 'ọkiósio',
sometimes: 'ọkiọvo',
'dry season': 'ọkiúvo',
village: 'ọkó (ighwre)',
'gift parcel': 'ọko',
present: 'ọko',
corner: 'ọ&#768kọ&#768kọ&#768',
thickness: 'ọkpá',
senior: 'ọkpáko',
pincers: 'ọkparibibẹ',
brassiere: 'ọkparivie',
piles: 'ọkpo',
'walking stick': 'ọkpọ&#768',
bamboo: 'ọkpọ&#768',
namesake: 'ọ&#768kpọ',
'squirrel like animal': 'ọkpọ&#768bia',
'fish box': 'ọ&#768kpọ&#768rho',
refrigerator: 'ọ&#768kpọ&#768rho',
mortuary: 'ọ&#768kpọ&#768rhorórivwi',
'blood bank': 'ọ&#768kpọ&#768rhorọ&#768bara',
short: 'ọkrẹkrẹ (krẹkrẹ)',
pupil: 'ọ&#768mẹ&#768ro <i><small>of eye</small></i>',
'nursing mothe': 'ọmiọvwọ', 
'woman having children': 'ọmiọvwọ',
native: 'ọ&#768mótọ',
indigene: 'ọ&#768mótọ', 
child: 'ọ&#768mọ&#768',
baby: 'ọ&#768mọbóba',
bushbaby: 'ọ&#768mọfófa',
'first born': 'ọ&#768mọkpáko',
'old person': 'ọ&#768mọ&#768mare',
stepchild: 'ọ&#768mọráruakpọ',
prince: 'ọ&#768mọrovie',
princess: 'ọ&#768mọrovie',
bastard: 'ọ&#768mọrọ&#768riọka',
'half brother': 'ọ&#768mọ&#768sẹ',
'half sister': 'ọ&#768mọ&#768sẹ',
boy: 'ọ&#768mọ&#768share',
girl: 'ọ&#768mọ&#768tẹ (ọgbọtọ), (ọkọkọ)',
spinster: 'ọ&#768mọ&#768tobẹ',
// ọ&#768mọ&#768tógbẹ n. old married woman who returns to her father's compound to stay
prophet: 'ọmraro',
'soldier fish': 'ọ&#768mwa',
trader: 'ọnéki',
yam: 'ọnẹ&#768',
policeman: 'ọnọ&#768kpa',
lobster: 'ọ&#768nya',
incubus: 'ọnyẹ',
weight: 'ọnyẹ&#768',
sardine: 'ọnyẹnyẹ&#768',
bee: 'ọ&#768nyọ',
'ray fish': 'ọpuọpuọ',
'tsetse fly': 'ọre',
meal: 'ọre',
honourable: 'ọrémuọghọkẹ',
witch: 'ọriéda (azẹ)',
wizard: 'ọriéda (azẹ)',
arrogance: 'ọriẹ',
porcupine: 'ọrígbẹ (evuẹ&#768n)',
bitterleaf: 'ọ&#768rígbo',
'weaver bird': 'ọriọka',
cobra: 'ọrobiebi',
lord: 'ọrovwori',
idol: 'ọrhá',
shrine: 'ọrhá',
visitor: 'ọrhárha', 
stranger: 'ọrhárha',
bachelor: 'ọrháre',
odour: 'ọrhe',
'native chalk': 'ọ&#768rhe',
plantain: 'ọrhẹ (ọdẹ)',
'security guard': 'ọrhẹrotọ <i><small>be it day or night</small></i>',
'tale bearere': 'ọrhierhia',
traitor: 'ọrhierhia',
growth: 'ọrho',
sieve: 'ọrhoghwo',
hot: 'ọrhorhorho (ọtuabọ)',
lover: 'ọse',
stepfather: 'ọ&#768sẹráruskpọ',
gorilla: 'ọsia<i><small>also a powerful person</small></i>',
hospital: 'ọsipíto',
hawk: 'ọso',
'father in law': 'ọ&#768sorọvwe',
'brother in law': 'ọ&#768sorọvwe',
straight: 'ọsoso (ovwiọvwiọ)',
full: 'ọsoso',
// ọsosuáda n. main part of a street
// ọsuere n. main part of a town
'town square': 'ọsuere',
humpback: 'ọ&#768súke',
man: 'ọ&#768share (ọhworhare)',
husband: 'ọ&#768shareórọvwe',
squirrel: 'ọtan',
spokesman: 'ọtota',
miser: 'ọtọke (ọtokpẹ)',
// ọtọrọ n. pattern of wrapper worn by men
slave: 'ọviẹ&#768',
one: 'ọvo',
only: 'ọ&#768vo',
certain: 'ọvo',
January: 'ọ&#768vuikpe',
same: 'ọvuọvo',
'one by one': 'ọvuọ&#768vó',
'step by step': 'ọvuọ&#768vó',
bride: 'ọvwá',
'wise man': 'ọvwághware',
'young palm': 'ọ&#768vwáre',
frond: 'ọ&#768vwe',
// ọvwe n. food prepared without salt
backbiter: 'ọvwéro',
'puff adder': 'ọvwerhotọ',
viper: 'ọvwẹ',
free: 'ọvwẹ&#768',
'lazy person': 'ọvwiẹrẹ',
rascal: 'ọvwísusu',
nuisance: 'ọvwísusu', 
vagabong: 'ọvwósoghoro',
coward: 'ọvwóshọ',
'non witch': 'ọvwóvwa',
'non wizard': 'ọvwóvwa',
'rough person': 'ọvwózighi',
confusionist: 'ọvwózighi',
fornicator: 'ọvwọ&#768farhiẹ',
stammerer: 'ọvwọrikọkọ',
'selfish person': 'ọvwúrhuru',
'greedy person': 'ọvwúrhuru',
// ọvwúvwohwo n. person without helper
enemy: 'ọvwréghrẹ',
priest: 'ọwára',
// ọwẹnẹwẹnẹ exp. statement that tends to examine an issue in alternative manner
// ọyavwemetẹ ,(ọyaọvwa) person who circumcises women
him: 'ọ&#768ye',
her: 'ọ&#768ye',
it: 'ọ&#768ye',
messenger: 'ọyikọ',
treasurer: 'ọyọrigho',
housemaid: 'ọyọrọmọ',

////////////////////////////// P p
flat: 'paparapa',
anyhow: 'patapata',
throbbing: 'pépé',
quietly: 'pẹ&#768pẹ&#768',
pet: 'pẹpẹ&#768',
watery: 'pẹtẹpẹtẹ',
// piápiá a. state of not being ripe
pointed: 'piọpiọpiọ',
'sharp tip': 'piọpiọpiọ',
'Portuguese person': 'potokri',
robust: 'pọkọpọko',
massive: 'pueké',
clean: 'puépué',
sluggish: 'puẹ&#768chẹ&#768',
'over ripe': 'puẹ&#768puẹ&#768',
'over cooked': 'puẹ&#768puẹ&#768',

/////////////////////////////// PH ph
urinate: 'phẹ',
expand: 'phẹn',
widen: 'phẹn',
'cave in': 'phẹn <i><small>e.g. of pit</small></i>',
jump: 'pho',
blow: 'phopho',
smoke: 'phopho',
gentle: 'phorophoro',
'not clearly': 'phorophoro',

///////////////////////////// R r
lick: 'rare',
our: 'ravware',
their: 'rayen',
eat: 're',
indefinite: 'reghereghe',
'in order to': 'rere',
'so that': 'rere',
third: 'rérhá',
sixth: 'résáa',
take: 'reyọ',
beg: 'rẹ',
plead: 'rẹ',
of: 'rẹ&#768',
fourth: 'rẹ&#768né',
eighth: 'rẹ&#768rére',
first: 'rẹ&#768sosuọ',
enjoy: 'riakpọ',
round: 'riariẹ',
wipe: 'rié',
lure: 'riẹ&#768riẹ&#768',
entice: 'riẹ&#768riẹ&#768', 
smooth: 'rioriorio',
seventh: 'ríghwrẹ&#768',
tenth: 'ríhwé',
tickle: 'ririe',
ninth: 'rírhiri',
fifth: 'ríyorin',
enter: 'ro',
big: 'rode',
think: 'roro',
add: 'roro', 
forget: 'rovwo',
your: 'rowán (rovwán)',
swallow: 'rọ',
marry: 'rọvwọ',
his: 'rọyen',
her: 'rọyen',
its: 'rọyen',
do: 'ru',
make: 'ru', 
poison: 'rua',
bewitch: 'rua',
'co operate': 'rukugbe',

////////////////////////////// RH rh
unite: 'rhá',
fly: 'rha',
paint: 'rhare',
bore: 'rharhe <i><small>hole</small></i>',
filter: 'rhẹ',
turn: 'rhẹriẹ',
swim: 'rhẹrhẹ',
open: 'rhie',
'non stop': 'rhiririn',
continuously: 'rhiririn',
return: 'rhívwi (hirhe)',
parboil: 'rho <i><small>of fish or meat halfway</small></i>',
again: 'rhoma',
bite: 'rhovwo',
rain: 'rhọ',
lay: 'rhọghọ <i><small>egg</small></i>',
agree: 'rhọvwe',
accept: 'rhọvwe',
bend: 'úgúgunu</br>rhuẹ <i><small>down</small></i>',
cover: 'rhurhu',

///////////////////////////// S s
shoot: 'sa',
burst: 'sa',
'break open': 'sa',
explode: 'sa',
select: 'sane',
different: 'sánsán',
smart: 'sasasa',
read: 'se',
refuse: 'se',
call: 'sé',
believe: 'segbúyóta',
dress: 'sẹ (heri) <i><small>for an occasion</small></i>',
write: 'si',
pull: 'si',
'so that': 'siẹnẹ&#768 (rere)',
'so as to': 'siẹnẹ&#768 (rere)',
'at once': 'siẹ&#768vuọ&#768vo (rharhiri)',
treat: 'sivwi',
contest: 'sivwi',
'struggle for': 'sivwi',
tap: 'so',
sing: 'so',
'shake hand': 'sobọ',
'hand shake': 'sobọ',
escort: 'su',
lead: 'su',
sticky: 'suesú',

///////////////////////// SH sh
// shá excl. word to chase away domestic animals
fall: 'she',
fail: 'she',
oppress: 'shenyẹ&#768',
far: 'shesheri',
sell: 'shẹ',
bury: 'shi',
'kneel down': 'shiguẹ',
crawl: 'shọ&#768rọ',
capsize: 'shu',

/////////////////////////////// T t
talk: 'ta',
say: 'ta',
// tá2 (chá) exp. word for rebuking
enough: 'téri',
// tẹ v.i fall out of grace, to be without honour
'tangled state': 'tighitighi',
'be removed': 'titi',
'be famous': 'titi',
where: 'tivọ',
dig: 'tọ',
'live long': 'tọ',
pick: 'tọre',
summon: 'tu',
purge: 'tue',
chew: 'tuọ&#768',
start: 'tuvwiyọ', 
begin: 'tuvwiyọ', 


//////////////////////////// U u
bone: 'ubeku',
wing: 'ubékpe',
seed: 'úbi',
charcoal: 'ubí',
soot: 'ubí',
tooth: 'úbiáko',
'dark complexion': 'úbiébi <i><small>very dark complexion</small></i>',
rib: 'úbiédada',
'palm nut': 'úbiédi',
kidney: 'úbiéhú',
angle: 'úbiényẹ',
stone: 'úbiérágha (úbiúkuta)',
cowry: 'úbígho',
clitoris: 'úbióhoró',
consonant: 'ubiotako',
vowel: 'ubiotaupho',
'ball by the ankle': 'úbiówọ',
spear: 'úbiri',
heart: 'úbiúdú',
'knee cap': 'úbiúgbo',
"adam's apple": 'úbiupho',
stick: 'úbiúrhe',
intestine: 'úbívun',
'hundred naira': 'úbrésiso',
'last born': 'ubrevwiẹ',
half: 'úbro',
state: 'úbrótọ',
room: 'úbrúwevwi',
advice: 'úchébro',
quantity: 'uché',
cookery: 'uchere',
pillar: 'uchivwo',
heel: 'úchúkówọ',
stump: 'úchuku',
amount: 'uchunu',
'male agama lizard': 'udene (ódókó)',
drink: 'udi',
wine: 'udi',
grasscutter: 'údí',
'cane rat': 'údí',
palmwine: 'udiáme (ọgọrọ)',
earthworm: 'údídẹ',
dignity: 'udidi',
charisma: 'udidi',
chimpanzee: 'údiéweri (okpe)',
cork: 'udió (orhá)',
riddle: 'údo',
chest: 'údú',
anxiety: 'úduébro',
// udje n. energetic Urhobo dance
farm: 'údjú (óghweri)',
trap: 'úfí',
fingernail: 'úfífobọ',
'sole rash': 'úfiówọ',
peace: 'úfuomá',
balcony: 'ugana (ibara)',
'fish trap': 'úgẹ&#768',
eagle: 'ugo',
shock: 'uguegue',
// úgba n. game of children involving jumping on the ground
simultaneously: 'úgbáda',
ladder: 'ugbakana (agbada)',
}


// ugbenu n. mountain/hill
// ugbére n. gonorrhoea
// ugbévwiẹ n. age-group
// ugbẹ n. pen, biro, pencil
// ugbẹáme n. pen, biro
// ugbẹóyaya n. pencil
// úgbévwére n. potsherd, broken earthenware
// ugbí n. seed-yam for planting
// ugbo n. bone between the knee and the ankle
// ugbóbọ n. arm
// ugbogbo n. caterpillar
// úgbónẹ n. speed
// ugbọmo n. child belt
// úgbọvó n. single wrapper worn by unmarried girl
// úgbugberi adv. across
// ugbuko (uko) n. back
// ugbunu (unu) n. mouth
// ughé n. spectacle
// ughegbe n. mirror
// úghére n. outskirts of a town or village
// úghéghẹ n. foolishness
// ughẹn n. period set aside for a woman to sleep with her husband
// ughọjọ (unọke) n. watch, clock
// ughwaka n. salt
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 44
// Urhobo PoS English gloss
// ughweri n. native salt
// ughwu n. death
// ughwru n. boundary
// úgrógro n. length
// uhéréviáso n. midnight
// uhérévie prep. middle, between
// úhóhi1 n. spiny part of the palm tree containing the leaves
// uhohi2 n. navel
// úhoho n. shadow
// úhwerhe n. sugar-cane
// úhwóvó
// (ihwegbẹọvo)
// num. eleven
// uje num. twenty
// uji n. theft
// ujórin num. hundred
// ujórha num. sixty
// ujórhagbẹihwe num. seventy
// újọ n. fly-whisk, object made of the tail of the horse used for decoration or
// dancing
// ujóne num. eighty
// ujónegbẹihwe num. ninety
// ujúvẹ num. forty
// ujúvẹgbẹihwe num. fifty
// uke1 n. hump, hunch
// uke2 n. style in Urhobo wrestling
// ukéké n. piece of stick used for setting trap
// ikeri n. number
// úké n. egg
// ukécha n. help
// úkérékpẹ n. brick
// ukẹun n. potash
// úkó n. cup
// ukodo n. food prepared with meat and yam or plantain together (mixed grill)
// ukókó1 n. association/society
// ukoko2 n. (tobacco) pipe
// ukokódia n. coconut palm
// ukoni n. kitchen
// ukori n. lump
// úkówọ n. top of the foot
// úkọ n. misfortune
// ukókóghọ n. small calabash used for storing medicine
// ukópa (ikọbọ) n. one kobo (1k)
// úkọvwá n. bridesmaid
// úku n. heritage
// ukujẹrẹ n. spoon
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 45
// Urhobo PoS English gloss
// ukúta n. rock
// ukútarírhibo
// (onanọ)
// n. grinding stone
// úkúwevwi n. back yard
// úkpavwre. n. bile
// ukpe1 n. year
// úkpe2 (éhwá) n. bed
// úkpébó n. white poplin
// ukpéré prep. instead of
// ukperi n. scandal
// úkpokpo (ókónọ) n. missile
// úkpókpógho n. disturbance
// úkpokpomá n. problem, worriedness
// ukpono1 n. lame person
// ukpono2 (úhwérhe) n. broom used in sweeping open places like compound while standing
// ukpotọ n. pothole
// úkpọkẹre n. gutter
// úmáko n. pepper fruit
// umẹ1 n. committee
// úmé2 n. cucumber
// umi n. sack used to squeeze water out of ground cassava
// úmióvwo n. destruction
// úmuému (úrubé) n. boil
// úmuwevwi n. cottage
// umwamwa n. belt used by women
// umwemwu n. sin
// umwáyá n. belt
// umwu (uhuvwu) n. drug
// une n. song
// unédi n. bunch of palm-nuts
// unó (ulóhó) n. oak [no oak trees in Nigeria]
// unórhẹ n. bunch of plantains
// unu n. hole
// unuémióvwo n. slander
// unuéphérẹ n. tribe
// unuékó n. quarrel
// unurévie n. nipple
// unurúwén n. nostril
// unúrhoro n. entrance/gate
// únúsọ n. anus
// úpé n. scar
// upéré (ubíbẹ) n. nail
// úphiáphiá n. cane/whip
// uphó1 n. throat
// úpho2 n. flesh
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 46
// Urhobo PoS English gloss
// úphóro n. feather
// úre n. totality
// úrié n. vein
// urí num. two hundred
// urí gbẹ ujórin num. three hundred
// uriórin num. one thousand
// uriórha num. six hundred
// iriórha gbẹ ujórin num. seven hundred
// uriọdja n. handkerchief
// urióne num. eight hundred
// urióne gbẹ ujórin num. nine hundred
// uriri n. glory
// úririẹ n. spice variety
// urívẹ num. four hundred
// urívẹ gbẹ ujórin num. five hundred
// úróko n. mile/kilometre
// úruému n. behaviour
// úruhré (úfí) n. rope
// urúrúvwen n. December
// úrhé n. tree
// úrhi n. law
// urhié n. river
// úrhié n. queue
// urhévwe n. destiny
// úrhióbọ n. finger
// úrhiówọ n. toe
// urhiórin n. September
// úrhiọke n. morning
// úrhirako n. fox
// urho1 (udo) n. mortar
// urhó2 n. gum tree sp.
// urhuẹ (ogbẹ) n. home
// úrhúghweri n. mangrove sp.
// úrhukpẹ (úkpẹ) n. lamp/light
// urhuru1 n. selfishness
// urhuru2 n. voice
// úrhúrhu n. tail
// urhúvwu n. street
// usa n. ring
// úsábọ n. scratch
// úságuẹ n. groundnut
// úse n. call
// úseki n. charm for business promotion
// úsekpe n. snail
// úseri n. proof, evidence
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 47
// Urhobo PoS English gloss
// usi1 n. fame
// úsi2 n. line
// usí3 n. starch
// úsiavwrẹ n. key
// usigá n. jigger
// usigho n. charm for wealth
// usú n. company
// úsuo n. government
// usuọvwa n. middleman (within the context of marriage)
// úshavwo n. okra
// usheneuwámwá n. twenty kobo (20k)
// ushi n. grave
// úshọvó n. November
// ushurhe n. axe
// utéhru n. steel
// útiẹ (ọsa) n. orange
// utohri n. pestle
// utóró n. three kobo (3k)
// utú n. north
// utudjéru (itijoro) n. scissors
// útughẹ n. hut
// utunédi n. bunch of palm-nuts from which the nuts had been removed
// útuomá n. charm that exposes someone to hatred
// ututa n. onion
// útúwevwi1
// (ótọrúwevwi)
// n. floor
// útúwevwi2 n. parlour
// uví1 n. paddle
// úvi2 a. real
// uvie n. kingdom
// uvo (ọren) n. sun, sunshine
// úvun n. bedroom
// uvuówọ n. calf
// uvumwemwu n. wickedness
// uvweri n. mourning
// uvwerhi n. reluctance
// úvwési (ipóko) n. pork
// úvwẹ n. chance
// uvwiẹ1 n. generation
// úvwié2 n. fart, foul air through the anus
// uvwiéreri n. shoal
// uvwré prep. midst
// uvwróvwró n. crevice
// uvwrọmọ n. grandchild
// úwén1 n. nose
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 48
// Urhobo PoS English gloss
// úwe2 n. thorn
// úwéré n. hardship
// uwerúyóno
// (isukuru)
// n. school
// uwevwi n. house
// uwevwiẹbe n. library
// uwevwiótọ n. bungalow
// uweyi n. errand
// úwén n. big fish-trap
// uwéga (ishọshi) n. church
// uwódi n. prison
// uwórha n. shrine
// úyérén1 n. greeting, appreciation
// uyere2 n. moat
// úyé n. fly
// úyédjọ n. mask
// úyóno n. lesson
// úyóta n. truth
// uyovwi n. head
// úyovwióta n. theme
// úzo (akora) n. antelope
// V v
// va1 v.t scold
// vá2 v.t butcher, break into parts (e.g. kola-nut)
// ve v.t bargain
// vẹ1 v.t disperse (of a crowd)
// vé2 prep. with
// vẹn3 (gunu) v.t bend
// vẹrhe adv. before
// vie v.t suck
// viẹ v.i cry
// vo v.t draw (e.g. water out of well)
// vó int. which
// vu v.t uproot
// vué v.t tell
// vughe v.t know/recognise
// vuvwu v.t roast
// vrẹ v.i rise
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 49
// Urhobo PoS English gloss
// VW vw
// vwá1 v.t revoke
// vwa2 int. word that relates to the state of a person or thing
// vware v.t wrap
// vwarié v.t repeat
// vwarhe v.i struggle
// vwavware a. red
// vwavwarhe (ghéghé) a. light
// vwavwe v.t weigh
// vwerhẹ v.i sleep
// vwevwerhe a. delicious
// vwẹ1 (mẹ) pron. me
// vwé2 prep. within, in
// vwẹghẹvwẹghẹ id. flat
// vwẹre a. fast
// vwi v.t stone
// vwié1 v.t deceive
// vwiẹ2 v.t born
// vwiọvwiọ id. straight
// vwirhi v.t break (with hands)
// vwiyẹ prep. into
// vwó1 (vwó) v.t use
// vwọ2 v.t assist a person in lifting a load to the head
// vwọvwe v.t disgrace
// vwu v.i swell
// vwre v.t turn (somebody/something) over
// vwrẹ v.t cut (with hands)
// vwro v.t argue
// vwru v.i survive
// W w
// wá1 (vwán) pron. you (coll.)
// wá2 (vwán) pron. you (obj.) (coll.)
// wa3 v.i pass (examination)
// wavrẹ v.t outstrip, overtake, pass
// weke id. word describing the vastness of an injury
// wene v.t change, transfer
// wéruo exp. please continue with your meal (coll.)
// wẹ1 (wọ) pron. you (sing.)
// wẹ2 pron. you (obj.) (sing.)
// wén3 poss.a. you (sing.)
// wẹn4 v.i breathe
// Urhobo Dictionary A.O. Ukere (1986) Web version by Roger Blench (2005)
// 50
// Urhobo PoS English gloss
// wẹnẹ v.t exchange words with
// wia v.t work
// wo1 v.t descend
// wo2 v.t put down (of load carried by a person)
// Y y
// yá1 v.t catch
// yan2 v.i walk/move
// yanra (ra) (kpo) v.i go
// yanrhe (mọ) (rhe) v.i come
// yárá a. bitter
// yavwe v.t circumcise
// yáyá a. dry
// Yéghwérẹ exp. safe journey!
// yena dem. that/those
// yeri v.t climb
// yerobuwevwi exp. greet all at home
// yẹghrẹ v.i struggle for balance
// yéré (éyé) conj. or
// yoma v.i boast
// yono v.t learn, study
// yoyovwi (yovwi) adv. fine, well
// yọre v.t hold
// Z z
// ze v.t offer, sacrifice
// zighizighi1
// (yaghayagha)
// id. rough
// roughly: 'zighizighi',